---
title: "R Notebook"
output: html_notebook
---

Funcions

```{r}

pow_two <- function (x, print_info) #Definir funciones

pow_two <- function (x, print_info=TRUE){ 
  y <- x ^ 2
  if (print_info){
    print(paste(x, "to the power two equals", y))
  }
  return (y)
  
}

result <- pow_two(3)
result

```

Function scoping

```{r}

pow_two <- function (x){
  y <- x ^ 2
  return (y)
}

pow_two(4)
 
```
R passes arguments by value

```{r}

triple <- function(x){
  x<- 3*x
  x
}

a <- 5
triple(a)
a

```

Others type of parameters


```{r}

linkedin <- c(16,9,13,5,2,17,14)

interpret <- function (num_views){
  if(num_views>15){
    print("you´re popular!")
    return(num_views)
  }
  else{
    print("Try to be more visible!")
    return(0)
  }
}

interpret(linkedin[1]) #se le envio el primer elemento (16)

#llamar a otra funcion dentro de una función

interpret_all <- function (views, return_sum = TRUE){
  count <- 0
  
  for(v in views){
    count <- count + interpret(v)
  }
  
  if(return_sum){
    return (count)
  }
  else{
    return(NULL)
  }

}

interpret_all(linkedin)



```
load an R Package

```{r}

library (ggplot2)

qplot(mtcars$wt, mtcars$hp)

```

Use Apply with R

lapply

```{r}

temp <- list(c(3,7,9,6,1), c(6,9,12,13,5), c(4,8,3,-1,-3), c(1,4,7,2,-2), c(5,7,9,4,2), c(-3,5,8,9,4), c(3,6,9,4,1))

lapply(temp, min) #dato de menor valor de cada colección

for (t in temp){
  print(min(t))
}

select <- function (x){
  print(paste("This collection contains total =", sum(x))) #suma los elementos de cada coleccion
}

list <- lapply(temp, select)
list

```

lapply and anonymous functions

```{r}

(function(x) {3 * x})(9)

pioners <- c("GAUSS:1777", "BAYES:1702", "PASCAL:1623", "PEARSON:1857")

split <- strsplit(pioners, split = ":") #devuelve una lista con cada elmento

split

split_low <- lapply(split, tolower) #aplica la conversion a minuscula a todos los elementos

split_low

names <- lapply(split_low, function(x){x[1]}) # para cada elemento imprime solo el primer elemento

names


years <- lapply(split_low, function(x){x[2]}) # para cada elemento imprime solo el segundo elemento

years



```
Use lapply with additional arguments


```{r}

select_el <- function(x, index){ #recibe 2 paramentros, si x es un vector, 
  x[index]                      #devuelve el elemento en la posición index
}

#split_low es la coleccion
#

names <- lapply (split_low, select_el, 1)
names

years <- lapply (split_low, select_el, 2)
years


```


sapply

```{r}

temp <- list(c(3,7,9,6,1), c(6,9,12,13,5), c(4,8,3,-1,-3), c(1,4,7,2,-2), c(5,7,9,4,2), c(-3,5,8,9,4), c(3,6,9,4,1))

extremes <- function (x){
  c(min=min(x), max= max(x))
}

lapply(temp, extremes)
sapply(temp, extremes)

#ejemplo 2

temp2 <- list(1,2,3,4,5)

func_temp2 <- function (x){
  x
}

lapply(temp2, func_temp2)
sapply(temp2, func_temp2)

```

vapply



```{r}

basics <- function (x){
  c(min=min(x), mean=mean(x), max=max(x))
}

lapply(temp, basics)
sapply(temp, basics)
vapply(temp, basics, numeric(3)) #agregar tipo de dato y recorrido


```
 
Ejemplo con letras  sapply, lapply, vapply

```{r}

temp3  <- c("Guatemala", "Salvador", "Honduras", "Nicaragua")

unique_letters <- function (name){
  bane <- gsub(" ", "", name)
  letters <- strsplit(name, split="")[[1]]
  unique(letters)
}

lapply(temp3, unique_letters)
sapply(temp3, unique_letters)
vapply(temp3, unique_letters, nchar(7)) #nos devuelve error porque no todos cumplen con 7 de longitud

```

Utilities

```{r}

errors <- c(1.9, -2.6, 4.0, -9.5, -3.4, 7.3)
print(sum(abs(round(errors))))

#ver información sobre funciones

?round

#

linkedin <- list(16, 9, 13, 5, 2, 17, 14)
facebook <- list(17, 7, 5, 16, 8, 13, 14)

li_vec <- unlist(linkedin) #Volver una lista a vector
li_vec

fb_vec <- unlist(facebook)
fb_vec

social_vec <- append(li_vec, fb_vec) #unir vectores y crear un solo vector con todos los elementos
social_vec


sort(social_vec, decreasing = TRUE) #ordenar descendente 


```

Expresiones regulares

grep & grepl

```{r}
emails <- c("john.doe@ivyleague.edu", "education@world.gov", "dalai.lama@peace.org",
            "invalid.edu", "quant@bigdatacollege.edu", "cookie.monster@sesame.tv")

grepl(pattern="edu", x=emails) #devuelve true para los elementos que cumplen el patron

hits <- grep(patter="edu", x=emails) #obtiene los indices que cumplen con el patron
hits

emails[hits] #imprime la colección con los indices
```

