---
title: "R Notebook"
output: html_notebook


```{r}
sets <- read_csv('sets.csv')
themes <- read_csv('themes.csv')
parts <- read_csv('parts.csv')
part_categories <- read_csv('part_categories.csv')

```

Selecting columns

```{r}
library(tidyverse)

counties <- read_csv('counties.csv')
counties

counties %>% 
  select(state, county, population, professional:production) #muestr columnas de professional a producction

counties %>% 
  select(state, county, population, ends_with("Work")) #las columnas que finalizan con la palabra Work

counties %>% 
  select(state, county, population, ends_with("Work"), starts_with("income")) #las columnas que finalizan con la palabra Work y que inician con income
  
counties %>% 
  select(state, county, population, ends_with("Work"), starts_with("income"), contains("per")) #las columnas que finalizan con la palabra Work, que inician con income, y que contengan per
  
```

Rename column

```{r}

counties %>% 
  count (state) %>%
  rename(num_counties=n)


#otra forma con select

counties %>% 
  select(state, county, poverty_rate = poverty)

```

Using Mutate

```{r}

counties %>% 
  transmute(state, county, population, density=population/land_area) %>%
  filter (population > 1000000) %>%
  arrange(density)

```


#EJERCICIO

vERBOS QUE SE PARECEN 

```{r}

counties %>%
  rename(unemployment_rate = unemployment) #renombrado de columna
  
counties %>%
  select(state,county, contains("Poverty"))  #unicamente obtiene las columnas que se le han indicado que contengan esa palabra
  
counties %>%
    mutate(fraction_women = women/population) #Agrega una columna

counties %>%
    transmute(state, county, employment_rate = employed /population) #columnas, mas la otra que estoy agregando
    

```

Joining Data with dplyr

```{r}
#View(sets)
sets
themes
```

```{r}
sets %>%
  inner_join(themes, by=c("theme_id" = "id"))
```





