---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

Carga de archivos

```{r}
inventories <- read_csv('inventories.csv')
invetory_parts <- read_csv('inventory_parts.csv')
colors <- read_csv('colors.csv')

inventories
invetory_parts
colors

```

```{r}
inventory_parts_joined <- inventories %>%
  inner_join(invetory_parts, by = c("id" = "inventory_id")) %>%
  select(-id, -version) %>% #las columnas menos id y version
  arrange(desc(quantity))

inventory_parts_joined

batmobile <- inventory_parts_joined %>%
  filter(set_num == "7784-1") %>%
  select(-set_num)

batmobile

batwing <- inventory_parts_joined %>%
  filter(set_num == "70916-1") %>%
  select(-set_num)

batwing

batmobile %>%
  inner_join(batwing, c("part_num", "color_id"), suffix = c("_batmobile", "_batwing"))

```


```{r}
parts %>%
  inner_join(invetory_parts, by = "part_num")

```

Multi Join

```{r}

sets %>%
  inner_join(inventories, by = "set_num") %>%
  inner_join(invetory_parts, by =c("id" = "inventory_id")) %>%
  inner_join(colors, by = c("color_id"="id"), suffix = c("_set", "_color")) %>%
  count(name_color) %>% #contador
  arrange(desc(n))

```

LEFT JOIN

```{r}

batmobile %>%
  inner_join(batwing, c("part_num", "color_id"), suffix = c("_batmobile", "_batwing"))

batmobile %>%
  left_join(batwing, c("part_num", "color_id"), suffix = c("_batmobile", "_batwing"))

```


```{r}
millennium_falcon <- inventory_parts_joined %>%
  filter(set_num == "7965-1")

millennium_falcon

star_destroyer <- inventory_parts_joined %>%
  filter(set_num == "75190-1")

star_destroyer

millennium_falcon %>%
  left_join(star_destroyer, by = c("part_num","color_id"), suffix=c("_falcon", "_star_destroyer"))

#2 juegos agrupados por color

millennium_falcon_colors <-
  millennium_falcon %>%
  group_by(color_id) %>%
  summarize(total_quiantity = sum(quantity))

millennium_falcon_colors

star_destroyer_colors <-
  star_destroyer %>%
  group_by(color_id) %>%
  summarize(total_quiantity = sum(quantity))

star_destroyer_colors

#Left Join

millennium_falcon_colors %>%
  left_join(star_destroyer_colors, by="color_id", suffix= c("_falcon", "_star_destroyer"))

```

Right Join

```{r}
parts %>%
  count(part_cat_id) %>%
  right_join(part_categories, by=c("part_cat_id" = "id")) %>%
  replace_na(list(n=0)) #Reemplazar el n/a


```

joining tables to themselves / union de tablas a sí mismas

```{r}

themes

themes %>%
  inner_join(themes, by= c("id" = "parent_id"), suffix= c("_parent", "_child"))

```





