---
title: "R Notebook"
output: html_notebook
---

crear dataframes

```{r}
name <- c("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")
type <- c("Terrestrial planet", "Terrestrial planet", "Terrestrial planet", 
          "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant")
diameter <- c(0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883)
rotation <- c(58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67)
rings <- c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE)
planets_df <- data.frame(name, type, diameter, rotation, rings)
planets_df

planets_df[1,3]

rings_vector <- planets_df$rings
rings_vector

planets_df[rings_vector,]

```


sorting

```{r}
a <- c(100,10,1000)
order(a)

b <- a[order(a)]
b

positions <- order(planets_df$diameter)
positions

planets_df[positions,]

```

listas


```{r}
my_vector <- 1:10
my_matrix <- matrix(1:9, ncol=3)
my_df <- planets_df[1:4,]

my_list 

```


Crear un named list


```{r}
names(my_list) <- v("Vector", "matrix", "data frame")
my_list


```
Selecting elements from a list

```{r}
my_list[[1]]
my_list[[1]][4]
my_list[[2]]
my_list[[2]][2,]
my_list[[2]][2,2]
my_list[[3]]
my_list[[3]][2:3, 1:2]
my_list[[3]][2:3, c("rotation", "rings")]
```



