---
title: "R Notebook"
output: html_notebook
---

R INTERMEDIATE

```{r}
3 == (2 + 1)
"intermediate" != "r"
TRUE != FALSE
"Rchitect" != "rchitect"

```

greater and less than


```{r}
-6 * 5 + 2 >= -10 + 1

"raining" <= "table"

TRUE > FALSE

"@" <= "?"

```
Compare vectors

```{r}

linkedin <- c(16,9,13,5,2,17,14)
facebook <- c(17,7,5,16,8,13,14)

linkedin > 15
facebook > 15

linkedin > facebook

views <- matrix (c(linkedin, facebook), nrow=2 , byrow=TRUE)
views

views == 13


```
Operaciones lógicas

```{r}

linkedin <= 10 & facebook == 13
views > 11 & views <5

```

the if statement

```{r}
medium <- "facebook"
num_views <- 14

if(medium == "linkedin"){
  print ("Showing LInkedin information")  
} else {
  print ("unknow medium")
}

if(num_views > 15){
  print("you are popular")
}else {
  print ("Try to be more visible!")
}



```


customize further: else if


```{r}

if(medium =="linkedin"){
  print("Showing Linkedin information")
} else if(medium == "facebook"){
  print("Showing facebook information")
} else{
   print ("Try to be more visible!")
}



```

else if 2.0

```{r}
number <- 11


if(number < 10){
  if(number < 5){
    result <- "extra small"
  }else{
    result <- "small"
  }
}else if (number < 100){
  result <- "medium"
}else{
result <- "large"
}

print(result)

```

Loops

```{r}

spped <- 64

while (spped > 30){
  print(paste("your spped is", spped))
  
  if(spped >= 48){
    print(paste("Slow down big time"))
    spped <- spped - 11
  }
  else{
    print(paste("Slow down big time"))
    spped <- spped - 6
  }
}

spped

```
Break

```{r}

speed <- 88

while (speed > 30){
  print(paste("your spped is", speed))
  
  if(speed > 80){
    break
  }
  
  if(speed > 48){
    print(paste("slow down big time", speed))
    speed <- speed - 11
  }
  
  else{
    print(paste("slow down", speed))
    speed <- speed - 6
  }
  
}

```

For

```{r}
linkedin <- c(16,9,13,5,2,17,14)

for(l in linkedin){
  print(l)
}

#Recorrer una lista

for (i in 1:length(linkedin)){
  print(linkedin[i])
}

```
Loop over a list

Recorrer una lista


```{r}
nyc <- list(pop=849320, boroughs=c("manhattan","bronx", "brooklyn","Queens","staten island"), capital =FALSE)

for (n in nyc){
  print(n)
}

for(i in 1:length(nyc)){
  if(i==2){
    for(j in 1:length(nyc[[i]])){
      print(nyc[[i]][j])
    }
  }
  else{
    print(nyc[[i]])
  }
}


```
loop over a matrix
recorrer una matriz

```{r}

views <- matrix(c(linkedin,facebook), nrow=2, byrow=TRUE)
views

for (row in 1:nrow(views)){
  for(col in 1:ncol(views)){
    print(paste("on row", row, "and column", col, "contanins", views[row,col]))
  }
}

```


